@url_dev=http://localhost:3055/v1/api

### signup
GET {{url_dev}}/product/drafts/all
Content-Type: application/json
x-api-key: f256e67f448d4a1b7a186bbb645c8e56d6df9a6f5a580966071b097dc4ac8a612ef4b9a9c4ac55de75ba0f34e499bf4dcebc7f321781a72a6a300cbee0acd4f6
x-client-id: 66366f86ab9ba72a07469e60
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM2NmY4NmFiOWJhNzJhMDc0NjllNjAiLCJlbWFpbCI6IlNob3BEZXZUaXBKc0BnbWFpbC5jb20iLCJpYXQiOjE3MTYwODU5NDAsImV4cCI6MTcxNjY5MDc0MH0.1ahL4b67slVk_TFhaQ5w76QWWsPTmZ2BI0t2aNpGBys
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM2NmY4NmFiOWJhNzJhMDc0NjllNjAiLCJlbWFpbCI6IlNob3BEZXZUaXBKc0BnbWFpbC5jb20iLCJpYXQiOjE3MTYwODU5NDAsImV4cCI6MTcxNjI1ODc0MH0.gwSsnxFvHpYBOAPMGHdMu7doZudYbnAtsX_-nJuPJ3A

# {
#     "name": "Shop TIPS",
#     "email": "ShopDevTipJs@gmail.com",
#     "password": "123"
# }


# {
#     "product_name": "Băng Quấn Bảo Vệ Khuỷu Tay Co Giản Tốt Tiện Dụng Khi Chơi Thể Thao Cho Nam",
#     "product_description": "Áo Thun Nam MRM kiểu dáng Regular fit tôn dáng cơ thể, làm nổi bật form người mặc thêm nam tính, khoẻ khoắn mà vẫn thoải mái vận động",
#     "product_price": 1234.000,
#     "product_shop": "6631bfa83sf94c740dd93c61e",
#     "product_type": "Clothing",
#     "product_thumb": "https://salt.tikicdn.com/cache/100x100/ts/product/d6/4f/c3/71f089380f605d172b54edf6aaa1877e.jpg.webp",
#     "product_quantity": 23,
#     "product_attributes": {
#         "brand": "MRM VietNam China",
#         "size": "XL",
#         "material": "Thun"
#     }
# }