@url_dev=http://localhost:3055/v1/api

### signup
# GET {{url_dev}}/product
# GET {{url_dev}}/product/search/ao thun
# GET {{url_dev}}/product/drafts/all
# GET {{url_dev}}/product/publish/all
# POST {{url_dev}}/product/publish/664972570529d443eefb454b
# POST {{url_dev}}/product/unpublish/66501d02a8e1b67ff890c068
POST {{url_dev}}/shop/login
# POST {{url_dev}}/product
Content-Type: application/json
x-api-key: bbcc91c7f35dd4ad2f55ba565bfe5f806608fc5c6161060d0eedd5e3ed7c3ae310fd7d3a1410f734f20e3d1722e13687396c3cd58085ae3b298f9aa2f350365c
# x-client-id: 66366f86ab9ba72a07469e60
# x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM2NmY4NmFiOWJhNzJhMDc0NjllNjAiLCJlbWFpbCI6IlNob3BEZXZUaXBKc0BnbWFpbC5jb20iLCJpYXQiOjE3MTY2MDI5OTQsImV4cCI6MTcxNzIwNzc5NH0.ORr5vFDmMONGwrp2uHgAlIqOoPMQahkv-H1HlKvzfp0
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM2NmY4NmFiOWJhNzJhMDc0NjllNjAiLCJlbWFpbCI6IlNob3BEZXZUaXBKc0BnbWFpbC5jb20iLCJpYXQiOjE3MTY2MDI5OTQsImV4cCI6MTcxNjc3NTc5NH0.DhziRimB9y2c_d4PI5CC0wZwdtQY8UD_pTEjwv5kZfY

{
    "name": "Shop TIPS",
    "email": "ShopDevTipJs@gmail.com",
    "password": "123"
}

{
    "product_name": "Product 002",
    "product_description": "Áo thun nam MRM kiểu dáng Regular fit tôn dáng cơ thể",
    "product_price": 1234,
    "product_shop": "66366f86ab9ba72a07469e60",
    "product_type": "Clothing",
    "product_thumb": "product_thumb",
    "product_quantity": 230,
    "product_attributes": {
        "brand": "MRM VietNam China",
        "size": "XL",
        "material": "Thun"
    }
}